In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
data = pd.read_csv("heart.csv")
data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [5]:
data.shape

(1025, 14)

In [6]:
data.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [35]:
data.duplicated().sum()

0

In [36]:
data[data.duplicated()]

Empty DataFrame
Columns: [age, sex, cp, trestbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, thal, target]
Index: []

In [37]:
data.drop_duplicates(inplace=True)

# Step 2 : Separate Input and out features

In [38]:
X = data.drop('target', axis=1)
y = data['target']

In [39]:
X

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     52    1   0       125   212    0        1      168      0      1.0   
1     53    1   0       140   203    1        0      155      1      3.1   
2     70    1   0       145   174    0        1      125      1      2.6   
3     61    1   0       148   203    0        1      161      0      0.0   
4     62    0   0       138   294    1        1      106      0      1.9   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
723   68    0   2       120   211    0        0      115      0      1.5   
733   44    0   2       108   141    0        1      175      0      0.6   
739   52    1   0       128   255    0        1      161      1      0.0   
843   59    1   3       160   273    0        0      125      0      0.0   
878   54    1   0       120   188    0        1      113      0      1.4   

     slope  ca  thal  
0        2   2     3  
1        0   0     3  
2        0   0     3  
3        2   1     3  
4        1   3     2  
..     ...  ..   ...  
723      1   0     2  
733      1   0     2  
739      2   1     3  
843      2   0     2  
878      1   1     3  

[302 rows x 13 columns]

In [40]:
y

0      0
1      0
2      0
3      0
4      0
      ..
723    1
733    1
739    0
843    0
878    0
Name: target, Length: 302, dtype: int64

In [41]:
y.value_counts()

target
1    164
0    138
Name: count, dtype: int64

In [44]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=43, test_size=.20)

In [45]:
from sklearn.linear_model import LogisticRegression

In [46]:
logr = LogisticRegression()

# Step 5: Model Fit

In [47]:
logr.fit(X_train,y_train)

C:\Users\Ahmed\New folder\anaconda3NEW\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [49]:
y_pred_train = logr.predict(X_train)
y_pred_train

array([1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0],
      dtype=int64)

In [50]:
count = 0
for t,p in zip(y_train,y_pred_train):
    if t==p:
        count+=1
count

209

In [51]:
len(X_train)

241

In [20]:
count/len(X_train)

0.8621951219512195

In [21]:
y_train

315     1
204     1
363     1
5       1
1017    0
       ..
835     0
192     1
629     0
559     0
684     0
Name: target, Length: 820, dtype: int64

# Step 6: Model Evaluation `

## Accuracy Score

In [52]:
from sklearn.metrics import accuracy_score
accuracy_score(y_train,y_pred_train)

0.8672199170124482

## Classification Report 

In [54]:
from sklearn.metrics import classification_report
print(classification_report(y_train,y_pred_train))

              precision    recall  f1-score   support

           0       0.89      0.79      0.84       107
           1       0.85      0.93      0.89       134

    accuracy                           0.87       241
   macro avg       0.87      0.86      0.86       241
weighted avg       0.87      0.87      0.87       241



In [53]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_train,y_pred_train))

[[ 85  22]
 [ 10 124]]


# Step 7 : Prediction on Test

In [55]:
y_pred_test = logr.predict(X_test)
y_pred_test

array([1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1], dtype=int64)

In [56]:
count = 0
for t,p in zip(y_test,y_pred_test):
    if t==p:
        count+=1
count

47

In [57]:
len(X_test)

61

In [58]:
count/len(X_test)

0.7704918032786885

## Classification Report 

In [63]:
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

           0       0.95      0.58      0.72        31
           1       0.69      0.97      0.81        30

    accuracy                           0.77        61
   macro avg       0.82      0.77      0.76        61
weighted avg       0.82      0.77      0.76        61



## Accuracy Score

In [59]:
print(accuracy_score(y_test,y_pred_test))

0.7704918032786885


In [62]:
print(confusion_matrix(y_test,y_pred_test))

[[18 13]
 [ 1 29]]


In [64]:
overfitt = 0.8672199170124482-0.7704918032786885

In [65]:
overfitt

0.09672811373375967

In [68]:
y_train.value_counts()

target
1    134
0    107
Name: count, dtype: int64

# Simple Hold Out Validation Cross Validation
  - ## Training Data
     - Partial Train Data
     - Valodation Data
   - ## Testing Data

# **K-Fold Cross Validation**
    - Training Data
    

In [69]:
from sklearn.model_selection import cross_val_score, KFold

In [76]:
num_folds = 5
kf = KFold(n_splits=num_folds, shuffle=True, random_state=2345)

In [78]:
import warnings
warnings.filterwarnings('ignore')

In [80]:
cross_val_results = cross_val_score(logr, X, y, cv=kf)

In [81]:
cross_val_results

array([0.86885246, 0.78688525, 0.88333333, 0.83333333, 0.85      ])

In [82]:
cross_val_results.mean()

0.8444808743169399